# Generated by Django 4.0.5 on 2022-06-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gender')),
            ],
        ),
        migrations.CreateModel(
            name='StyleWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylewebsite_text', models.CharField(max_length=300)),
                ('url', models.URLField(verbose_name='Site URL')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.style')),
            ],
        ),
    ]
